/********************************************************************************
** Form generated from reading UI file 'InfoBasePage.ui'
**
** Created: Tue Jun 27 11:36:45 2017
**      by: Qt User Interface Compiler version 4.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_INFOBASEPAGE_H
#define UI_INFOBASEPAGE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_InfoBasePage
{
public:
    QFrame *frameTop1;
    QLabel *lblStopWatch;
    QPushButton *btnStopWatchStart;
    QFrame *frameStatus;
    QLabel *label_2;
    QLabel *labelDate;
    QFrame *frame;
    QPushButton *btnActiveStatus;
    QPushButton *btnOasStatus;
    QPushButton *btnUcsStatus;
    QPushButton *btnCtdStatus;
    QPushButton *btnCicsStatus;
    QPushButton *btnNavStatus;
    QPushButton *btnReturnHMI;
    QPushButton *btnReturnSNS;
    QPushButton *btnReturnONA;
    QPushButton *btnCritical;
    QPushButton *btnCaviting;
    QPushButton *btnReturnHMI_10;
    QPushButton *btnSonarStatus;
    QFrame *frame_2;
    QPushButton *btnStopWatchReset;
    QLabel *lblLVLUnit;
    QLabel *lblPLS;
    QLabel *lblLENVal;
    QLabel *lblLVLVal;
    QLabel *lblLEN;
    QLabel *lblLVL;
    QLabel *lblPLSVal;
    QLabel *lblBWVal;
    QLabel *lblCFUnit;
    QLabel *lblBWUnit;
    QLabel *lblCFVal;
    QLabel *lblCF;
    QLabel *lblREL;
    QLabel *lblRELVal;
    QLabel *lblBW;
    QLabel *lblLENUnit;
    QLabel *lblRELUnit;
    QLabel *lblSoundVelUnit;
    QLabel *lblSoundVelvalue;
    QLabel *lblSoundVel;
    QLabel *lblDepthUnit;
    QLabel *lblCourse;
    QLabel *lblSpeedVal;
    QLabel *lblDepthVal;
    QLabel *lblCourseUnit;
    QLabel *lblSpeed;
    QLabel *lblSpeedUnit;
    QLabel *lblDepth;
    QLabel *lblCourseVal;
    QLabel *lblLongitudeVal;
    QLabel *lblLatitude;
    QLabel *lblLongitude;
    QLabel *lblLatitudeVal;
    QLabel *lblLongitudeUnit;
    QLabel *lblLatitudeUnit;
    QLabel *labelTime;
    QPushButton *btnPage;
    QPushButton *btnSysMode;
    QLabel *lblPage;
    QLabel *lblSysMode;
    QLabel *lblLongitude_2;
    QLabel *lblLongitude_3;
    QLabel *lblhdval;
    QLabel *lblSwval;
    QLabel *lblLongitudeUnit_2;
    QLabel *lblLongitudeUnit_3;
    QFrame *frame_3;

    void setupUi(QDialog *InfoBasePage)
    {
        if (InfoBasePage->objectName().isEmpty())
            InfoBasePage->setObjectName(QString::fromUtf8("InfoBasePage"));
        InfoBasePage->resize(1600, 1200);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(InfoBasePage->sizePolicy().hasHeightForWidth());
        InfoBasePage->setSizePolicy(sizePolicy);
        InfoBasePage->setStyleSheet(QString::fromUtf8(""));
        frameTop1 = new QFrame(InfoBasePage);
        frameTop1->setObjectName(QString::fromUtf8("frameTop1"));
        frameTop1->setGeometry(QRect(0, 0, 1600, 121));
        frameTop1->setStyleSheet(QString::fromUtf8("background-color:rgb(0, 0, 0);\n"
"\n"
""));
        frameTop1->setFrameShape(QFrame::Box);
        frameTop1->setFrameShadow(QFrame::Raised);
        lblStopWatch = new QLabel(frameTop1);
        lblStopWatch->setObjectName(QString::fromUtf8("lblStopWatch"));
        lblStopWatch->setGeometry(QRect(360, 10, 61, 16));
        QFont font;
        font.setPointSize(10);
        lblStopWatch->setFont(font);
        lblStopWatch->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        btnStopWatchStart = new QPushButton(frameTop1);
        btnStopWatchStart->setObjectName(QString::fromUtf8("btnStopWatchStart"));
        btnStopWatchStart->setGeometry(QRect(340, 30, 51, 23));
        btnStopWatchStart->setFont(font);
        btnStopWatchStart->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        frameStatus = new QFrame(frameTop1);
        frameStatus->setObjectName(QString::fromUtf8("frameStatus"));
        frameStatus->setGeometry(QRect(730, 87, 630, 30));
        frameStatus->setStyleSheet(QString::fromUtf8("background-color:rgb(0, 0, 0);\n"
""));
        frameStatus->setFrameShape(QFrame::NoFrame);
        frameStatus->setFrameShadow(QFrame::Raised);
        frameStatus->setLineWidth(0);
        label_2 = new QLabel(frameTop1);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(230, 12, 91, 20));
        labelDate = new QLabel(frameTop1);
        labelDate->setObjectName(QString::fromUtf8("labelDate"));
        labelDate->setGeometry(QRect(220, 10, 91, 16));
        labelDate->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 0);"));
        frame = new QFrame(frameTop1);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(0, 82, 1366, 39));
        frame->setStyleSheet(QString::fromUtf8(""));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        btnActiveStatus = new QPushButton(frame);
        btnActiveStatus->setObjectName(QString::fromUtf8("btnActiveStatus"));
        btnActiveStatus->setGeometry(QRect(807, 8, 71, 23));
        btnActiveStatus->setFont(font);
        btnActiveStatus->setStyleSheet(QString::fromUtf8("background-color: rgb(128,128,128);"));
        btnOasStatus = new QPushButton(frame);
        btnOasStatus->setObjectName(QString::fromUtf8("btnOasStatus"));
        btnOasStatus->setGeometry(QRect(884, 8, 71, 23));
        btnOasStatus->setFont(font);
        btnOasStatus->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnUcsStatus = new QPushButton(frame);
        btnUcsStatus->setObjectName(QString::fromUtf8("btnUcsStatus"));
        btnUcsStatus->setGeometry(QRect(970, 8, 71, 23));
        btnUcsStatus->setFont(font);
        btnUcsStatus->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnCtdStatus = new QPushButton(frame);
        btnCtdStatus->setObjectName(QString::fromUtf8("btnCtdStatus"));
        btnCtdStatus->setGeometry(QRect(1059, 8, 71, 23));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(128, 128, 128, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 251, 242, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(212, 209, 201, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(85, 83, 80, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(113, 111, 107, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(212, 211, 208, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush9(QColor(170, 167, 161, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        btnCtdStatus->setPalette(palette);
        btnCtdStatus->setFont(font);
        btnCtdStatus->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnCicsStatus = new QPushButton(frame);
        btnCicsStatus->setObjectName(QString::fromUtf8("btnCicsStatus"));
        btnCicsStatus->setGeometry(QRect(1134, 8, 71, 23));
        btnCicsStatus->setFont(font);
        btnCicsStatus->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128);"));
        btnNavStatus = new QPushButton(frame);
        btnNavStatus->setObjectName(QString::fromUtf8("btnNavStatus"));
        btnNavStatus->setGeometry(QRect(1210, 8, 71, 23));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        btnNavStatus->setPalette(palette1);
        btnNavStatus->setFont(font);
        btnNavStatus->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128);"));
        btnReturnHMI = new QPushButton(frame);
        btnReturnHMI->setObjectName(QString::fromUtf8("btnReturnHMI"));
        btnReturnHMI->setGeometry(QRect(80, 8, 61, 23));
        btnReturnHMI->setFont(font);
        btnReturnHMI->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnReturnSNS = new QPushButton(frame);
        btnReturnSNS->setObjectName(QString::fromUtf8("btnReturnSNS"));
        btnReturnSNS->setGeometry(QRect(10, 8, 61, 23));
        btnReturnSNS->setFont(font);
        btnReturnSNS->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnReturnONA = new QPushButton(frame);
        btnReturnONA->setObjectName(QString::fromUtf8("btnReturnONA"));
        btnReturnONA->setGeometry(QRect(150, 8, 61, 23));
        btnReturnONA->setFont(font);
        btnReturnONA->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnCritical = new QPushButton(frame);
        btnCritical->setObjectName(QString::fromUtf8("btnCritical"));
        btnCritical->setGeometry(QRect(280, 8, 111, 23));
        btnCritical->setFont(font);
        btnCritical->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnCaviting = new QPushButton(frame);
        btnCaviting->setObjectName(QString::fromUtf8("btnCaviting"));
        btnCaviting->setGeometry(QRect(400, 8, 81, 23));
        btnCaviting->setFont(font);
        btnCaviting->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnReturnHMI_10 = new QPushButton(frame);
        btnReturnHMI_10->setObjectName(QString::fromUtf8("btnReturnHMI_10"));
        btnReturnHMI_10->setGeometry(QRect(490, 8, 111, 23));
        btnReturnHMI_10->setFont(font);
        btnReturnHMI_10->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        btnSonarStatus = new QPushButton(frame);
        btnSonarStatus->setObjectName(QString::fromUtf8("btnSonarStatus"));
        btnSonarStatus->setGeometry(QRect(730, 8, 71, 23));
        btnSonarStatus->setFont(font);
        btnSonarStatus->setMouseTracking(false);
        btnSonarStatus->setAutoFillBackground(false);
        btnSonarStatus->setStyleSheet(QString::fromUtf8("background-color: rgb(128,128,128);"));
        frame_2 = new QFrame(frameTop1);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(0, 0, 1366, 82));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        btnStopWatchReset = new QPushButton(frame_2);
        btnStopWatchReset->setObjectName(QString::fromUtf8("btnStopWatchReset"));
        btnStopWatchReset->setGeometry(QRect(396, 30, 51, 23));
        btnStopWatchReset->setFont(font);
        btnStopWatchReset->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        lblLVLUnit = new QLabel(frame_2);
        lblLVLUnit->setObjectName(QString::fromUtf8("lblLVLUnit"));
        lblLVLUnit->setGeometry(QRect(1080, 46, 31, 16));
        lblLVLUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblPLS = new QLabel(frame_2);
        lblPLS->setObjectName(QString::fromUtf8("lblPLS"));
        lblPLS->setGeometry(QRect(975, 4, 25, 16));
        lblPLS->setFont(font);
        lblPLS->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblLENVal = new QLabel(frame_2);
        lblLENVal->setObjectName(QString::fromUtf8("lblLENVal"));
        lblLENVal->setGeometry(QRect(1015, 24, 31, 20));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Sans Serif"));
        font1.setPointSize(10);
        font1.setBold(false);
        font1.setWeight(50);
        lblLENVal->setFont(font1);
        lblLENVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblLVLVal = new QLabel(frame_2);
        lblLVLVal->setObjectName(QString::fromUtf8("lblLVLVal"));
        lblLVLVal->setGeometry(QRect(1015, 46, 31, 16));
        lblLVLVal->setFont(font1);
        lblLVLVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblLEN = new QLabel(frame_2);
        lblLEN->setObjectName(QString::fromUtf8("lblLEN"));
        lblLEN->setGeometry(QRect(975, 24, 25, 16));
        lblLEN->setFont(font);
        lblLEN->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblLVL = new QLabel(frame_2);
        lblLVL->setObjectName(QString::fromUtf8("lblLVL"));
        lblLVL->setGeometry(QRect(975, 46, 23, 16));
        lblLVL->setFont(font);
        lblLVL->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblPLSVal = new QLabel(frame_2);
        lblPLSVal->setObjectName(QString::fromUtf8("lblPLSVal"));
        lblPLSVal->setGeometry(QRect(1015, 4, 41, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Sans Serif"));
        font2.setBold(false);
        font2.setItalic(false);
        font2.setWeight(50);
        lblPLSVal->setFont(font2);
        lblPLSVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblBWVal = new QLabel(frame_2);
        lblBWVal->setObjectName(QString::fromUtf8("lblBWVal"));
        lblBWVal->setGeometry(QRect(1215, 4, 41, 16));
        lblBWVal->setFont(font2);
        lblBWVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblCFUnit = new QLabel(frame_2);
        lblCFUnit->setObjectName(QString::fromUtf8("lblCFUnit"));
        lblCFUnit->setGeometry(QRect(1280, 23, 31, 16));
        lblCFUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblBWUnit = new QLabel(frame_2);
        lblBWUnit->setObjectName(QString::fromUtf8("lblBWUnit"));
        lblBWUnit->setGeometry(QRect(1280, 4, 31, 16));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Sans Serif"));
        font3.setItalic(false);
        lblBWUnit->setFont(font3);
        lblBWUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblCFVal = new QLabel(frame_2);
        lblCFVal->setObjectName(QString::fromUtf8("lblCFVal"));
        lblCFVal->setGeometry(QRect(1215, 23, 31, 20));
        lblCFVal->setFont(font1);
        lblCFVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblCF = new QLabel(frame_2);
        lblCF->setObjectName(QString::fromUtf8("lblCF"));
        lblCF->setGeometry(QRect(1175, 23, 21, 16));
        lblCF->setFont(font);
        lblCF->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblREL = new QLabel(frame_2);
        lblREL->setObjectName(QString::fromUtf8("lblREL"));
        lblREL->setGeometry(QRect(1175, 45, 26, 16));
        lblREL->setFont(font);
        lblREL->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblRELVal = new QLabel(frame_2);
        lblRELVal->setObjectName(QString::fromUtf8("lblRELVal"));
        lblRELVal->setGeometry(QRect(1215, 45, 31, 16));
        lblRELVal->setFont(font1);
        lblRELVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblBW = new QLabel(frame_2);
        lblBW->setObjectName(QString::fromUtf8("lblBW"));
        lblBW->setGeometry(QRect(1175, 4, 23, 16));
        lblBW->setFont(font);
        lblBW->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblLENUnit = new QLabel(frame_2);
        lblLENUnit->setObjectName(QString::fromUtf8("lblLENUnit"));
        lblLENUnit->setGeometry(QRect(1080, 24, 43, 16));
        lblLENUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblRELUnit = new QLabel(frame_2);
        lblRELUnit->setObjectName(QString::fromUtf8("lblRELUnit"));
        lblRELUnit->setGeometry(QRect(1280, 45, 31, 16));
        lblRELUnit->setFont(font3);
        lblRELUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblSoundVelUnit = new QLabel(frame_2);
        lblSoundVelUnit->setObjectName(QString::fromUtf8("lblSoundVelUnit"));
        lblSoundVelUnit->setGeometry(QRect(615, 60, 43, 16));
        lblSoundVelUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblSoundVelvalue = new QLabel(frame_2);
        lblSoundVelvalue->setObjectName(QString::fromUtf8("lblSoundVelvalue"));
        lblSoundVelvalue->setGeometry(QRect(540, 60, 55, 16));
        lblSoundVelvalue->setFont(font1);
        lblSoundVelvalue->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblSoundVel = new QLabel(frame_2);
        lblSoundVel->setObjectName(QString::fromUtf8("lblSoundVel"));
        lblSoundVel->setGeometry(QRect(510, 60, 21, 16));
        lblSoundVel->setFont(font);
        lblSoundVel->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblDepthUnit = new QLabel(frame_2);
        lblDepthUnit->setObjectName(QString::fromUtf8("lblDepthUnit"));
        lblDepthUnit->setGeometry(QRect(615, 41, 31, 16));
        lblDepthUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblCourse = new QLabel(frame_2);
        lblCourse->setObjectName(QString::fromUtf8("lblCourse"));
        lblCourse->setGeometry(QRect(510, 4, 21, 16));
        lblCourse->setFont(font);
        lblCourse->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblSpeedVal = new QLabel(frame_2);
        lblSpeedVal->setObjectName(QString::fromUtf8("lblSpeedVal"));
        lblSpeedVal->setGeometry(QRect(540, 19, 55, 21));
        lblSpeedVal->setFont(font1);
        lblSpeedVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblDepthVal = new QLabel(frame_2);
        lblDepthVal->setObjectName(QString::fromUtf8("lblDepthVal"));
        lblDepthVal->setGeometry(QRect(540, 41, 55, 16));
        lblDepthVal->setFont(font1);
        lblDepthVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblCourseUnit = new QLabel(frame_2);
        lblCourseUnit->setObjectName(QString::fromUtf8("lblCourseUnit"));
        lblCourseUnit->setGeometry(QRect(615, 4, 31, 16));
        lblCourseUnit->setFont(font3);
        lblCourseUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblSpeed = new QLabel(frame_2);
        lblSpeed->setObjectName(QString::fromUtf8("lblSpeed"));
        lblSpeed->setGeometry(QRect(510, 22, 21, 16));
        lblSpeed->setFont(font);
        lblSpeed->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblSpeedUnit = new QLabel(frame_2);
        lblSpeedUnit->setObjectName(QString::fromUtf8("lblSpeedUnit"));
        lblSpeedUnit->setGeometry(QRect(615, 22, 31, 16));
        lblSpeedUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblDepth = new QLabel(frame_2);
        lblDepth->setObjectName(QString::fromUtf8("lblDepth"));
        lblDepth->setGeometry(QRect(510, 41, 21, 16));
        lblDepth->setFont(font);
        lblDepth->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblCourseVal = new QLabel(frame_2);
        lblCourseVal->setObjectName(QString::fromUtf8("lblCourseVal"));
        lblCourseVal->setGeometry(QRect(540, 4, 55, 16));
        lblCourseVal->setFont(font2);
        lblCourseVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblLongitudeVal = new QLabel(frame_2);
        lblLongitudeVal->setObjectName(QString::fromUtf8("lblLongitudeVal"));
        lblLongitudeVal->setGeometry(QRect(730, 60, 55, 20));
        lblLongitudeVal->setFont(font1);
        lblLongitudeVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblLatitude = new QLabel(frame_2);
        lblLatitude->setObjectName(QString::fromUtf8("lblLatitude"));
        lblLatitude->setGeometry(QRect(690, 40, 31, 20));
        lblLatitude->setFont(font);
        lblLatitude->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblLongitude = new QLabel(frame_2);
        lblLongitude->setObjectName(QString::fromUtf8("lblLongitude"));
        lblLongitude->setGeometry(QRect(690, 60, 31, 20));
        lblLongitude->setFont(font);
        lblLongitude->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblLatitudeVal = new QLabel(frame_2);
        lblLatitudeVal->setObjectName(QString::fromUtf8("lblLatitudeVal"));
        lblLatitudeVal->setGeometry(QRect(730, 40, 55, 16));
        lblLatitudeVal->setFont(font2);
        lblLatitudeVal->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblLongitudeUnit = new QLabel(frame_2);
        lblLongitudeUnit->setObjectName(QString::fromUtf8("lblLongitudeUnit"));
        lblLongitudeUnit->setGeometry(QRect(800, 22, 31, 16));
        lblLongitudeUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        lblLatitudeUnit = new QLabel(frame_2);
        lblLatitudeUnit->setObjectName(QString::fromUtf8("lblLatitudeUnit"));
        lblLatitudeUnit->setGeometry(QRect(800, 4, 31, 16));
        lblLatitudeUnit->setFont(font3);
        lblLatitudeUnit->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 255)"));
        labelTime = new QLabel(frame_2);
        labelTime->setObjectName(QString::fromUtf8("labelTime"));
        labelTime->setGeometry(QRect(221, 45, 91, 30));
        labelTime->setStyleSheet(QString::fromUtf8("color: rgb(0, 255, 0);"));
        btnPage = new QPushButton(frame_2);
        btnPage->setObjectName(QString::fromUtf8("btnPage"));
        btnPage->setEnabled(true);
        btnPage->setGeometry(QRect(80, 50, 131, 23));
        btnPage->setFont(font);
        btnPage->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128);\n"
"\n"
""));
        btnSysMode = new QPushButton(frame_2);
        btnSysMode->setObjectName(QString::fromUtf8("btnSysMode"));
        btnSysMode->setEnabled(true);
        btnSysMode->setGeometry(QRect(80, 10, 130, 23));
        btnSysMode->setFont(font);
        btnSysMode->setStyleSheet(QString::fromUtf8("background-color:rgb(128,128,128)"));
        lblPage = new QLabel(frame_2);
        lblPage->setObjectName(QString::fromUtf8("lblPage"));
        lblPage->setGeometry(QRect(10, 50, 46, 13));
        lblPage->setFont(font);
        lblPage->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblSysMode = new QLabel(frame_2);
        lblSysMode->setObjectName(QString::fromUtf8("lblSysMode"));
        lblSysMode->setGeometry(QRect(2, 14, 71, 16));
        lblSysMode->setFont(font);
        lblSysMode->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)\n"
""));
        lblLongitude_2 = new QLabel(frame_2);
        lblLongitude_2->setObjectName(QString::fromUtf8("lblLongitude_2"));
        lblLongitude_2->setGeometry(QRect(690, 20, 31, 20));
        lblLongitude_2->setFont(font);
        lblLongitude_2->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblLongitude_3 = new QLabel(frame_2);
        lblLongitude_3->setObjectName(QString::fromUtf8("lblLongitude_3"));
        lblLongitude_3->setGeometry(QRect(690, 3, 31, 20));
        lblLongitude_3->setFont(font);
        lblLongitude_3->setStyleSheet(QString::fromUtf8("color:rgb(0,255,0)"));
        lblhdval = new QLabel(frame_2);
        lblhdval->setObjectName(QString::fromUtf8("lblhdval"));
        lblhdval->setGeometry(QRect(730, 3, 55, 16));
        lblhdval->setFont(font2);
        lblhdval->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblSwval = new QLabel(frame_2);
        lblSwval->setObjectName(QString::fromUtf8("lblSwval"));
        lblSwval->setGeometry(QRect(730, 20, 55, 16));
        lblSwval->setFont(font2);
        lblSwval->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblLongitudeUnit_2 = new QLabel(frame_2);
        lblLongitudeUnit_2->setObjectName(QString::fromUtf8("lblLongitudeUnit_2"));
        lblLongitudeUnit_2->setGeometry(QRect(800, 40, 31, 16));
        lblLongitudeUnit_2->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        lblLongitudeUnit_3 = new QLabel(frame_2);
        lblLongitudeUnit_3->setObjectName(QString::fromUtf8("lblLongitudeUnit_3"));
        lblLongitudeUnit_3->setGeometry(QRect(800, 60, 31, 16));
        lblLongitudeUnit_3->setStyleSheet(QString::fromUtf8("color:rgb(255, 170, 0)"));
        frame_2->raise();
        lblStopWatch->raise();
        btnStopWatchStart->raise();
        frameStatus->raise();
        label_2->raise();
        labelDate->raise();
        frame->raise();
        frame_3 = new QFrame(InfoBasePage);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(1366, 0, 233, 121));
        frame_3->setAutoFillBackground(false);
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);

        retranslateUi(InfoBasePage);

        QMetaObject::connectSlotsByName(InfoBasePage);
    } // setupUi

    void retranslateUi(QDialog *InfoBasePage)
    {
        InfoBasePage->setWindowTitle(QApplication::translate("InfoBasePage", "Dialog", 0, QApplication::UnicodeUTF8));
        lblStopWatch->setText(QApplication::translate("InfoBasePage", "00:00:00", 0, QApplication::UnicodeUTF8));
        btnStopWatchStart->setText(QApplication::translate("InfoBasePage", "Start", 0, QApplication::UnicodeUTF8));
        label_2->setText(QString());
        labelDate->setText(QApplication::translate("InfoBasePage", "xx/xx/xx", 0, QApplication::UnicodeUTF8));
        btnActiveStatus->setText(QApplication::translate("InfoBasePage", "Active", 0, QApplication::UnicodeUTF8));
        btnOasStatus->setText(QApplication::translate("InfoBasePage", "OAS", 0, QApplication::UnicodeUTF8));
        btnUcsStatus->setText(QApplication::translate("InfoBasePage", "UCS", 0, QApplication::UnicodeUTF8));
        btnCtdStatus->setText(QApplication::translate("InfoBasePage", "CTD", 0, QApplication::UnicodeUTF8));
        btnCicsStatus->setText(QApplication::translate("InfoBasePage", "CICS", 0, QApplication::UnicodeUTF8));
        btnNavStatus->setText(QApplication::translate("InfoBasePage", "NAV ", 0, QApplication::UnicodeUTF8));
        btnReturnHMI->setText(QApplication::translate("InfoBasePage", "HMI", 0, QApplication::UnicodeUTF8));
        btnReturnSNS->setText(QApplication::translate("InfoBasePage", "SNS", 0, QApplication::UnicodeUTF8));
        btnReturnONA->setText(QApplication::translate("InfoBasePage", "ONA", 0, QApplication::UnicodeUTF8));
        btnCritical->setText(QApplication::translate("InfoBasePage", "Critical Error", 0, QApplication::UnicodeUTF8));
        btnCaviting->setText(QApplication::translate("InfoBasePage", "Caviting", 0, QApplication::UnicodeUTF8));
        btnReturnHMI_10->setText(QApplication::translate("InfoBasePage", "Torpedo Alert", 0, QApplication::UnicodeUTF8));
        btnSonarStatus->setText(QApplication::translate("InfoBasePage", "Sonar", 0, QApplication::UnicodeUTF8));
        btnStopWatchReset->setText(QApplication::translate("InfoBasePage", "Reset", 0, QApplication::UnicodeUTF8));
        lblLVLUnit->setText(QApplication::translate("InfoBasePage", "dB", 0, QApplication::UnicodeUTF8));
        lblPLS->setText(QApplication::translate("InfoBasePage", "PLS", 0, QApplication::UnicodeUTF8));
        lblLENVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblLVLVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblLEN->setText(QApplication::translate("InfoBasePage", "LEN", 0, QApplication::UnicodeUTF8));
        lblLVL->setText(QApplication::translate("InfoBasePage", "LVL", 0, QApplication::UnicodeUTF8));
        lblPLSVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblBWVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblCFUnit->setText(QApplication::translate("InfoBasePage", "Hz", 0, QApplication::UnicodeUTF8));
        lblBWUnit->setText(QApplication::translate("InfoBasePage", "Hz", 0, QApplication::UnicodeUTF8));
        lblCFVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblCF->setText(QApplication::translate("InfoBasePage", "CF", 0, QApplication::UnicodeUTF8));
        lblREL->setText(QApplication::translate("InfoBasePage", "REL", 0, QApplication::UnicodeUTF8));
        lblRELVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblBW->setText(QApplication::translate("InfoBasePage", "BW", 0, QApplication::UnicodeUTF8));
        lblLENUnit->setText(QApplication::translate("InfoBasePage", "m/sec", 0, QApplication::UnicodeUTF8));
        lblRELUnit->setText(QApplication::translate("InfoBasePage", "Deg", 0, QApplication::UnicodeUTF8));
        lblSoundVelUnit->setText(QApplication::translate("InfoBasePage", "m/sec", 0, QApplication::UnicodeUTF8));
        lblSoundVelvalue->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblSoundVel->setText(QApplication::translate("InfoBasePage", "SV", 0, QApplication::UnicodeUTF8));
        lblDepthUnit->setText(QApplication::translate("InfoBasePage", "M", 0, QApplication::UnicodeUTF8));
        lblCourse->setText(QApplication::translate("InfoBasePage", "CO", 0, QApplication::UnicodeUTF8));
        lblSpeedVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblDepthVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblCourseUnit->setText(QApplication::translate("InfoBasePage", "Deg", 0, QApplication::UnicodeUTF8));
        lblSpeed->setText(QApplication::translate("InfoBasePage", "SP", 0, QApplication::UnicodeUTF8));
        lblSpeedUnit->setText(QApplication::translate("InfoBasePage", "Kts", 0, QApplication::UnicodeUTF8));
        lblDepth->setText(QApplication::translate("InfoBasePage", "D", 0, QApplication::UnicodeUTF8));
        lblCourseVal->setText(QApplication::translate("InfoBasePage", "<html><head/><body><p>xxx</p></body></html>", 0, QApplication::UnicodeUTF8));
        lblLongitudeVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblLatitude->setText(QApplication::translate("InfoBasePage", "LAT", 0, QApplication::UnicodeUTF8));
        lblLongitude->setText(QApplication::translate("InfoBasePage", "LNG", 0, QApplication::UnicodeUTF8));
        lblLatitudeVal->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblLongitudeUnit->setText(QApplication::translate("InfoBasePage", "Deg", 0, QApplication::UnicodeUTF8));
        lblLatitudeUnit->setText(QApplication::translate("InfoBasePage", "Deg", 0, QApplication::UnicodeUTF8));
        labelTime->setText(QApplication::translate("InfoBasePage", "xx:xx:xx", 0, QApplication::UnicodeUTF8));
        btnPage->setText(QApplication::translate("InfoBasePage", "SPMS", 0, QApplication::UnicodeUTF8));
        btnSysMode->setText(QApplication::translate("InfoBasePage", "NORMAL", 0, QApplication::UnicodeUTF8));
        lblPage->setText(QApplication::translate("InfoBasePage", "PAGE", 0, QApplication::UnicodeUTF8));
        lblSysMode->setText(QApplication::translate("InfoBasePage", "SYSMODE", 0, QApplication::UnicodeUTF8));
        lblLongitude_2->setText(QApplication::translate("InfoBasePage", "Sw", 0, QApplication::UnicodeUTF8));
        lblLongitude_3->setText(QApplication::translate("InfoBasePage", "Hd", 0, QApplication::UnicodeUTF8));
        lblhdval->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblSwval->setText(QApplication::translate("InfoBasePage", "xxx", 0, QApplication::UnicodeUTF8));
        lblLongitudeUnit_2->setText(QApplication::translate("InfoBasePage", "N", 0, QApplication::UnicodeUTF8));
        lblLongitudeUnit_3->setText(QApplication::translate("InfoBasePage", "E", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class InfoBasePage: public Ui_InfoBasePage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_INFOBASEPAGE_H
